# Práctica 3. Estructuras de control. 

1.  Crea un programa que te clasifique una variable numérica en función de la escala 

Suspendido/ Aprobado/ Notable / Excelente 

In [38]:
# Primero pedimos la entrada de una nota manualmente. 
y = input ( "introduce una nota del 0 al 10 :   ",  )
y = float (y) # al convertirla en decimal,nos aseguramos la entrada de cualquier nota 

# Creamos una función que transforme una variable numércia a una escala de valoración no numérica. 
def nota ( x ): 
    if   x >= 0  and x < 5 : 
        return  " Suspendido "
    if x >= 5  and x <=7 : 
        return   " Aprobado" 
    if x > 7 and x <=9 : 
        return   " Notable" 
    if x > 9 and x <=10 : 
        return   " Excelente"

# Con lo siguiente nos aseguramos que la nota esté dentro del rango de 0 a 10 y aplicamos la conversión
# mediante la funcion llamada nota (x)

if y <0 or y >10 : 
    print ( " Valor de nota fuera de rango ")
    y2 = float (input ( "introduce una nota del 0 al 10 :   ",  ))
    print( nota (y2))
else : 
    print ( nota ( y))

introduce una nota del 0 al 10 :   11
 Valor de nota fuera de rango 
introduce una nota del 0 al 10 :   7.5
 Notable


2. Introduce dos números cualesquiera y crea un programa que diga cuál es más grande que el otro o si son iguales


In [44]:
k = float ( input ( "introduce un valor para la primera variable :  "))
l= float ( input ( "introduce otro valor para la segunda variable :  "))

if k > l : 
    print ( k , " es más grande que " , l )
elif l > k : 
    print ( l , " es más grande que " , k )
else:
    print ( k , " es igual a ", l)
        

introduce un valor para la primera variable :  4
introduce otro valor para la segunda variable :  4
4.0  es igual a  4.0


3.  Crea un programa que te pregunte tu nombre, y te solicite un número.

Si el número es 0, debería mostrar un mensaje de error. De lo contrario,

debería mostrar el nombre repetido tantas veces como indique el número

In [47]:
# Se introducen las dos variables mediante teclado
nom = input ( " introduce tu nombre ")
num= abs (int (input( " introduce un número entero ")))
# Pedimos que el número sea entero para asegurarnos que la multiplicación 
# de cadenas de caracteres sea posible 
# Luego, creamos el programa para que nos calcule la operación, dejando 
# fuera la multiplicaicón por cero
if num == 0 : 
    print ( " Error, ha puesto el cero y no es válido")
else : 
    print ( num* nom )
    

 introduce tu nombre Gerard 
 introduce un número entero 5
Gerard Gerard Gerard Gerard Gerard 


4. Crea un programa que dada una lista cualquiera,

te diga si es simétrica o no. 

Si lo es, que te diga cuántos elementos tiene.

In [127]:
import random 
import numpy as np

# sea una lista cualquiera, pongamos un matriz n*m,  
n = int ( input ( "introduce un número filas : "))
m = int ( input ( "introduce un número columnas : "))
list = []

# creamos un bucle para hacer una matriz aleatoria con valores enteros de una cifra 
for j in range (0,m):
    col =  [] # el nombre de col hace referencia a columna 
    for i in range (0,n):
        col. append ( random.randint ( 0,1)* ((-1)**random.randint ( 1,2) ) )
    list. append (col)    
        


# para que sea simétrica como mínimo su ha de ser una matriz cuadrada, tal que m =n 
    mat = np.array ( list) # usamos numpy para calcular la transpuesta
if m != n : 
    print ( " la matriz no es simétrica y contiene ", len ( mat ), "columnas")
else:
    
    dif = np.array_equal(mat,mat.T) # sea dif, la diferencia de las matrices,dando un valor cierto  si 
                                     # tienen los mismos elementos
    print ( " la lista es:  "  )
    print ( mat)
    print ( "\n ")
    print (" matriz transpuesta es : " )
    print ( mat.T)
    print ( "\n ")
    if dif == True: 
        print ( " es una lista simétrica ")
    else : 
        print ( " la matriz no es simétrica y contiene ", len ( mat ), "columnas") 
        
    


introduce un número filas : 3
introduce un número columnas : 3
 la lista es:  
[[ 1 -1  0]
 [-1  1  0]
 [ 0  0  0]]

 
 matriz transpuesta es : 
[[ 1 -1  0]
 [-1  1  0]
 [ 0  0  0]]

 
 es una lista simétrica 


5.  Crea un programa que dada una lista, te diga cuántos números coinciden con su posición

In [131]:
serie = [] # sea la lista a comparar de 10 elementos, que crearemos de forma aleatoria 
for r in range ( 0,10 ):
    serie.append ( random.randint (0, 9 ))
print ( serie )

tot = 0 # sea una variable auxiliar para contar cuantos números coinciden con su posición.
for s in serie : 
    if s== serie [s]:
        tot = tot +1
print ( " la cantidad de elementos de la serie, que coincide su valor con su posición es : ", tot)
        

[9, 0, 4, 7, 3, 0, 6, 3, 8, 8]
 la cantidad de elementos de la serie, que coincide su valor con su posición es :  3
